# Generated by Django 4.1.2 on 2022-11-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('published_date', models.DateField()),
                ('expired_date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('posted_by', models.CharField(max_length=100)),
                ('attachment', models.FileField(upload_to='pdfs/')),
            ],
        ),
    ]
